const rusLang = document.querySelector('.rus');
const engLang = document.querySelector('.eng');
const rusLangMenu = document.querySelector('.rus-menu');
const engLangMenu = document.querySelector('.eng-menu');

rusLang.onclick = function(){
    rusLang.style.backgroundColor = '#E5E5E5';
    rusLang.style.color = 'black';
    engLang.style.backgroundColor = '#F3F3F3';
    engLang.style.color = '#444444';
    rusLangMenu.style.backgroundColor = '#E5E5E5';
    rusLangMenu.style.color = 'black';
    engLangMenu.style.backgroundColor = 'white';
    engLangMenu.style.color = '#444444';
    document.querySelector('.content-text').textContent = 'В наших лучших дизайнерских работах Заказчик найдет интерьеры в различных стилях: от строгого современного минимализма до роскошного, богато декорированного, от недорогих, бюджетных решений до элитных и уникальных.';
    document.querySelector('.content-head1').textContent = 'Гармония';
    document.querySelector('.content-head2').textContent = 'Концептуальная студия';
    document.querySelector('.read-text').textContent = 'Читать далее';
    document.querySelector('.view-text').textContent = 'Посмотреть проект';
    document.querySelector('.view').style.width = '150px';
    document.querySelector('.menu-close').style.marginLeft = '445px';
    document.querySelector('.nav-right-interior').textContent = 'Интерьер';
    document.querySelector('.nav-right-shop').textContent = 'Магазин';
    document.querySelector('.menu-close-text').textContent = 'Закрыть';
    document.querySelector('.main-text1').textContent = 'Интерьер';
    document.querySelector('.main-text1').style.marginLeft = '-30px';
    document.querySelector('.main-text2').textContent = 'Архитектура';
}

engLang.onclick = function(){
    rusLang.style.backgroundColor = '#F3F3F3';
    rusLang.style.color = '#444444';
    engLang.style.backgroundColor = '#E5E5E5';
    engLang.style.color = 'black';
    rusLangMenu.style.backgroundColor = 'white';
    rusLangMenu.style.color = '#444444';
    engLangMenu.style.backgroundColor = '#E5E5E5';
    engLangMenu.style.color = 'black';
    document.querySelector('.content-text').textContent = 'In our best design works, the Customer will find interiors in various styles, from strict modern minimalism to luxurious, richly decorated, from inexpensive, budgetary solutions to elite and unique.';
    document.querySelector('.content-head1').textContent = 'Harmony';
    document.querySelector('.content-head2').textContent = 'Concept studio';
    document.querySelector('.read-text').textContent = 'Read More';
    document.querySelector('.view-text').textContent = 'View project';
    document.querySelector('.view').style.width = '105px';
    document.querySelector('.menu-close').style.marginLeft = '423px';
    document.querySelector('.nav-right-interior').textContent = 'Interior';
    document.querySelector('.nav-right-shop').textContent = 'Shop';
    document.querySelector('.menu-close-text').textContent = 'Close';
    document.querySelector('.main-text1').textContent = 'Interior';
    document.querySelector('.main-text2').textContent = 'Architecture';
}

rusLangMenu.onclick = function(){
    rusLang.style.backgroundColor = '#E5E5E5';
    rusLang.style.color = 'black';
    engLang.style.backgroundColor = '#F3F3F3';
    engLang.style.color = '#444444';
    rusLangMenu.style.backgroundColor = '#E5E5E5';
    rusLangMenu.style.color = 'black';
    engLangMenu.style.backgroundColor = 'white';
    engLangMenu.style.color = '#444444';
    document.querySelector('.content-text').textContent = 'В наших лучших дизайнерских работах Заказчик найдет интерьеры в различных стилях: от строгого современного минимализма до роскошного, богато декорированного, от недорогих, бюджетных решений до элитных и уникальных.';
    document.querySelector('.content-head1').textContent = 'Гармония';
    document.querySelector('.content-head2').textContent = 'Концептуальная студия';
    document.querySelector('.read-text').textContent = 'Читать далее';
    document.querySelector('.view-text').textContent = 'Посмотреть проект';
    document.querySelector('.view').style.width = '150px';
    document.querySelector('.menu-close').style.marginLeft = '445px';
    document.querySelector('.nav-right-interior').textContent = 'Интерьер';
    document.querySelector('.nav-right-shop').textContent = 'Магазин';
    document.querySelector('.menu-close-text').textContent = 'Закрыть';
    document.querySelector('.main-text1').textContent = 'Интерьер';
    document.querySelector('.main-text1').style.marginLeft = '-30px';
    document.querySelector('.main-text2').textContent = 'Архитектура';
}

engLangMenu.onclick = function(){
    rusLang.style.backgroundColor = '#F3F3F3';
    rusLang.style.color = '#444444';
    engLang.style.backgroundColor = '#E5E5E5';
    engLang.style.color = 'black';
    rusLangMenu.style.backgroundColor = 'white';
    rusLangMenu.style.color = '#444444';
    engLangMenu.style.backgroundColor = '#E5E5E5';
    engLangMenu.style.color = 'black';
    document.querySelector('.content-text').textContent = 'In our best design works, the Customer will find interiors in various styles, from strict modern minimalism to luxurious, richly decorated, from inexpensive, budgetary solutions to elite and unique.';
    document.querySelector('.content-head1').textContent = 'Harmony';
    document.querySelector('.content-head2').textContent = 'Concept studio';
    document.querySelector('.read-text').textContent = 'Read More';
    document.querySelector('.view-text').textContent = 'View project';
    document.querySelector('.view').style.width = '105px';
    document.querySelector('.menu-close').style.marginLeft = '423px';
    document.querySelector('.nav-right-interior').textContent = 'Interior';
    document.querySelector('.nav-right-shop').textContent = 'Shop';
    document.querySelector('.menu-close-text').textContent = 'Close';
    document.querySelector('.main-text1').textContent = 'Interior';
    document.querySelector('.main-text2').textContent = 'Architecture';
}